name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Initialize
      run: ls

    - name: Install dependencies
      run: make pre-build

    # - name: Lint
    #   run: |
    #     go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.46.2
    #     make lint
      
    # - name: Security Scan
    #   run: |
    #     go install github.com/securego/gosec/v2/cmd/gosec@latest
    #     make sec
      
    - name: Tests
      run: make test

  deployment:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - uses: actions/checkout@v3
    - name: Environ File
      run: |
        echo "\
        DATABASE_USER=${vars.DATABASE_USER}\
        DATABASE_PASS=${secrets.DATABASE_PASS}\
        DATABASE_HOST=${vars.DATABASE_HOST}\
        DATABASE_NAME=${vars.DATABASE_NAME}\
        DATABASE_COLLECTION=${vars.DATABASE_COLLECTION}\
        REDIS_HOST=${vars.REDIS_HOST}\
        REDIS_PORT=${vars.REDIS_PORT}\
        REDIS_PASS=${secrets.REDIS_PASS}\
        REDIS_DB=${vars.REDIS_DB}\
        JWT_SECRET_KEY=${vars.JWT_SECRET_KEY}\
        " >> .env.prod
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Deploy
      run: make docker.push
