name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on

    steps:
    - uses: actions/checkout@v3

    - name: initialize
      run: ls

    - name: Install dependencies
      run: make pre-build

    - name: Lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.51.1
        golangci-lint --version
        make lint
      
    - name: Security Scan
      run: |
        curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $(go env GOPATH)/bin vX.Y.Z
        gosec --version
        make sec
      
    - name: Tests
      run: make test
      
    - name: Dockerize
      run: make docker.push
