name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on

    steps:
    - uses: actions/checkout@v3

    - name: initialize
      run: ls

    - name: Install dependencies
      run: make pre-build

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.46
      
    - name: Security Scan
      uses: securego/gosec@master
      with:
        args: ./...
      
    - name: Tests
      run: make test
      
    - name: Dockerize
      run: make docker.push
