name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Initialize
      run: ls

    - name: Install dependencies
      run: make pre-build

    # - name: Lint
    #   run: |
    #     go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.46.2
    #     make lint
      
    # - name: Security Scan
    #   run: |
    #     go install github.com/securego/gosec/v2/cmd/gosec@latest
    #     make sec
      
    - name: Tests
      run: make test

  deployment:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - uses: actions/checkout@v3
    - name: Environ File
      run: |
        echo "\
        DATABASE_USER=${{vars.DATABASE_USER}}\n\
        DATABASE_PASS=${{secrets.DATABASE_PASS}}\n\
        DATABASE_HOST=${{vars.DATABASE_HOST}}\n\
        DATABASE_NAME=${{vars.DATABASE_NAME}}\n\
        DATABASE_COLLECTION=${{vars.DATABASE_COLLECTION}}\n\
        REDIS_HOST=${{vars.REDIS_HOST}}\n\
        REDIS_PORT=${{vars.REDIS_PORT}}\n\
        REDIS_PASS=${{secrets.REDIS_PASS}}\n\
        REDIS_DB=${{vars.REDIS_DB}}\n\
        JWT_SECRET_KEY=${{vars.JWT_SECRET_KEY}}\n\
        " >> .env.prod && cat .env.prod
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
    - name: Deploy
      run: make docker.push
