name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on

    steps:
    - uses: actions/checkout@v3

    - name: initialize
      run: ls

    - name: Install dependencies
      run: make pre-build

    # - name: Lint
    #   run: |
    #     go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.46.2
    #     make lint
      
    # - name: Security Scan
    #   run: |
    #     go install github.com/securego/gosec/v2/cmd/gosec@latest
    #     make sec
      
    - name: Tests
      run: make test
      
    - name: Dockerize
      run: make docker.push
